server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://rxbymcvfmdhltk:8e0b2b0bc535a2c0fbcb819bbc11c961394fc3c09065b50a1ffc54af02027aee@ec2-54-90-13-87.compute-1.amazonaws.com:5432/dd1s5p5d9rcs5m
    username: rxbymcvfmdhltk
    password: 8e0b2b0bc535a2c0fbcb819bbc11c961394fc3c09065b50a1ffc54af02027aee
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none


application:
  description: Projeto criado para o Bootcamp DIO - Santander
